spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123
  jpa:
    properties:
      hibernate:
        default_schema: project
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    table: project_schema_version
    baseline-version: 0
    locations: classpath:db/migration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: a833d47a8361dc
    password: 4906ce8687759c
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

vars:
  security:
    enable: false

server:
  port: 8090

token:
  ttl: 3600000
  secret: "https://www.youtube.com/watch?v=VBUMYOYJISc"

admin:
  username: admin
  email: admin@admin.com
  password: admin

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui



