package com.mobylab.springbackend.exception;

public enum ErrorCodes {
    ASSET_NOT_FOUND,
    SYMBOL_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    INVALID_PREFIX,
    INTERNAL_ERROR,
    PORTFOLIO_NOT_FOUND,
    UNAUTHORIZED_ACCESS,
    INVALID_CREDENTIAL,
    INVALID_QUANTITY,
    INVALID_PRICE,
    ORDER_CREATION_FAILED,
}
